### ISSUE TITLE
Pen Issues

### ISSUE THREAD

**Issue by Leonlmao** [personalizedrefrigerator/joplin-plugin-freehand-drawing#15]
After i add a picture when i try to draw it dissapear when i release the pen. But if i use the mouse instead, it works just fine.

**Comment by personalizedrefrigerator** [comment]
This may be fixed by [this upstream commit](https://github.com/personalizedrefrigerator/js-draw/commit/ea0aa399d31bb1cd04cc557c0cab15b667752dfd), which is included in [v2.12.0](https://github.com/personalizedrefrigerator/joplin-plugin-freehand-drawing/releases/tag/v2.12.0).

**Change summary:** Pointer events have an [`isPrimary` attribute](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/isPrimary). `js-draw` previously assumed that strokes would always be drawn with a pointer marked with `isPrimary`. [This commit](https://github.com/personalizedrefrigerator/js-draw/commit/ea0aa399d31bb1cd04cc557c0cab15b667752dfd) allows `js-draw` to handle strokes where `isPrimary` is `false`.

**Note**: This might not be the same as the [upstream issue](https://github.com/personalizedrefrigerator/js-draw/issues/71).

**Comment by Leonlmao** [comment]
Thank you so much, it works perfectly now!
